#include "vpx_config.h"

#if CONFIG_DOUBANGO

#include "doubango_config.h"

#include <mmintrin.h> /* MMX */
#include <xmmintrin.h> /* SSE */
#include <emmintrin.h> /* SSE2 */

#if DOUBANGO_ASM_INLINE && !defined(_M_X64)
#	define COPY_MEM16X16_MOVE_PREPARE() \
		__asm mov eax, dword ptr[src] /* eax = src */ \
		__asm mov ecx, dword ptr[dst] /* ecx = dst*/
#	define COPY_MEM16X16_MOVE_ALIGNED() \
		__asm movdqa xmm0, xmmword ptr[eax] \
		__asm movdqa xmmword ptr[ecx], xmm0
#	define COPY_MEM16X16_MOVE_UNALIGNED() \
		__asm movdqu xmm0, xmmword ptr[eax] \
		__asm movdqa xmmword ptr[ecx], xmm0
#	define COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() \
		COPY_MEM16X16_MOVE_ALIGNED() \
		__asm add eax, dword ptr[src_stride] \
		__asm add ecx, dword ptr[dst_stride]
#	define COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() \
		COPY_MEM16X16_MOVE_UNALIGNED() \
		__asm add eax, dword ptr[src_stride] \
		__asm add ecx, dword ptr[dst_stride]
#else
#	define COPY_MEM16X16_MOVE_PREPARE() ;
#	define COPY_MEM16X16_MOVE_ALIGNED() _mm_store_si128((__m128i*)dst, _mm_load_si128((__m128i*)src));
#	define COPY_MEM16X16_MOVE_UNALIGNED() _mm_store_si128((__m128i*)dst, _mm_loadu_si128((__m128i*)src));
#	define COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED(); src += src_stride; dst += dst_stride;
#	define COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED(); src += src_stride; dst += dst_stride;
#endif /* DOUBANGO_ASM_INLINE && !defined(_M_X64) */

void vp8_copy_mem16x16_doubango_sse2(unsigned char *src, int src_stride, unsigned char *dst/*always aligned*/, int dst_stride/*always aligned*/)
{
	if (DOUBANGO_IS_ALIGNED(src, 16) && DOUBANGO_IS_ALIGNED(src_stride, 16)) {
		COPY_MEM16X16_MOVE_PREPARE()
		COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT()
		COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT()
		COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT()
		COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_ALIGNED()
	}
	else {
		COPY_MEM16X16_MOVE_PREPARE()
		COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT()
		COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT()
		COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT()
		COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED_AND_GOTO_NEXT() COPY_MEM16X16_MOVE_UNALIGNED()
	}
}

#endif /* CONFIG_DOUBANGO */
